version: '3.0'

services:

  blazegraph:
    image: vcity/blazegraph-cors
    ports:
      - "${BLAZEGRAPH_PORT}:8080"
    networks:
      - cluster-net
  udviz1:
    build:
      context: ./ud-viz-context
      args:
        indexFile: src/index_3D.js
    ports:
      - ${UD_VIZ_PORT1}:8000
    networks:
      - cluster-net
  udviz2:
    build:
      context: ./ud-viz-context
      args:
        indexFile: src/index_json.js
    ports:
      - ${UD_VIZ_PORT2}:8000
    networks:
      - cluster-net
  udviz3:
    build:
      context: ./ud-viz-context
      args:
        indexFile: src/index_static_nodes.js
    ports:
      - ${UD_VIZ_PORT3}:8000
    networks:
      - cluster-net

networks:

  cluster-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
      com.docker.network.bridge.name: br-cluster
