version: '3.0'

services:

  blazegraph:
    image: vcity/blazegraph-cors
    ports:
      - "${BLAZEGRAPH_PORT}:8080"
  udviz1:
    build:
      context: ./ud-viz-context
      args:
        indexFile: src/index_3D.js
    ports:
      - ${UD_VIZ_PORT1}:8000
  udviz2:
    build:
      context: ./ud-viz-context
      args:
        indexFile: src/index_json.js
    ports:
      - ${UD_VIZ_PORT2}:8000
