PREFIX bldg: <https://dataset-dl.liris.cnrs.fr/rdf-owl-urban-data-ontologies/Ontologies/CityGML/3.0/building#>

SELECT ?subject
WHERE {
  {
    ?subject ?predicate ?object ;
      a ?subjectType .
  
    OPTIONAL { ?object a ?objectType }
  }
  FILTER(?subjectType = bldg:Building)
  FILTER(?objectType != owl:NamedIndividual)
}